# Generated by Django 6.0.2 on 2026-02-06 13:25

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
