# Generated by Django 6.0.2 on 2026-02-09 14:39

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='profile_images/covers/'),
        ),
    ]
